name: Build and Push Docker Images

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Spring Boot App
        working-directory: api
        run: |
          chmod +x ./mvnw
          ./mvnw clean package -DskipTests

      - name: Prepare API Docker artifact
        run: |
          mkdir -p api/release
          cp api/target/krishisetu-api-0.0.1-SNAPSHOT.jar api/release/app.jar

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build API Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/krishisetu-api:latest ./api

      - name: Build Web Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/krishisetu-web:latest ./web

      - name: Push API Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/krishisetu-api:latest

      - name: Push Web Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/krishisetu-web:latest
